### ISSUE TITLE
Remove recipe directions text table

### ISSUE THREAD

**Issue by jayaddison** [openculinary/backend#91]
We have not been providing `directions` (aka instructions) text via the API since https://github.com/openculinary/api/commit/b8d4a763cb899c38803cc8eeb3fd737296b81dbf (2021-03-01), nor storing complete `directions` text since a5a314e2ea15bffffaa7706bb52c7d2b4fd671b4 (2023-10-16).  We have continued to store the filtered direction text -- nouns and verbs describing preparation steps -- in the hope that we can use these to construct preparation diagrams for recipes, as per the service vision statement -- but this does not appear to be on the immediate horizon, and legal advice received indicates that processing and storing recipe instructional text incurs some risk.

Until we can renavigate a safer route to construct recipe preparation diagrams, we should drop the recipe `directions` text from the database.  This should also allow us to remove instructional text retrieval and parsing from the `crawler` service and data pipeline, both potential performance and simplicity benefits.

**Comment by jayaddison** [comment]
This implies that we will also remove `equipment` search functionality from the service, because we identify equipment relevant to each recipe by inspecting the instructional text.

**Comment by jayaddison** [comment]
Most of the preparations for this are now ready, I think -- but they haven't all been tested yet.  Here's a plan for how to test and deploy them:

### 1. Prepare the frontend client application

Objective: upgrade the client so that it provides messaging to users that query-by-equipment will no longer be available.  Also, opportunistically remove the long-unused recipe `directions` table from the client.

- [ ] Merge openculinary/frontend#263 and openculinary/frontend#265 into a testing branch.
- [ ] Create a sample search API response containing the `equipment_search_unavailable` refinement indicator.
- [ ] Confirm that the application handles the message as intended.
- [ ] If possible, confirm that the database upgrade works as intended (e.g. by choosing a starred-recipe from the sample API response before the upgrade, and ensuring that it is retained)
- [ ] Deploy these changes to production.

### 2. Upgrade the Search API to remove query-by-equipment functionality.

Objective: unblock storage-level cleanup of recipe `directions` text in the search engine index and database.

- [ ] Test openculinary/api#125
- [ ] Deploy openculinary/api#125 to production

### 3. Remove query-by-equipment functionality from the UI

- [ ] Test openculinary/frontend#264
- [ ] Deploy openculinary/frontend#264 to production

### 4. Cleanup: remove recipe `directions` text from backend and storage-level components

- [ ] Deploy #92 (already tested) to production.
- [ ] Deploy openculinary/crawler#33 (unit-tested) to production.
- [ ] Remove recipe `directions` and `equipment` references from the search engine index mapping ( https://github.com/openculinary/backend/blob/214bf07c199a590eadbe550e6b324291fa1b1f70/scripts/update-recipe-index.py )
- [ ] Reindex all recipes
- [ ] Take a backup -- but do not yet publish it -- and inspect to ensure that it no longer contains recipe `directions` text in either the database or search index snapshots.
- [ ] Publish the latest backups.

**Comment by jayaddison** [comment]
Re-opening until frontend application, cleanup tasks, and backups are completed.

**Comment by jayaddison** [comment]
> Edit: note that no explicit recipe `directions`-related entries existed in the mapping creation script (but these would have been implicitly created at indexing-time if recipe `directions` had appeared in the ingested documents).

NB: Double-checked and confirmed that, as expected, intended and hoped, no `directions` property entry is found in the existing recipes search engine index mapping.

**Comment by jayaddison** [comment]
> Re-opening until frontend application, cleanup tasks, and backups are completed.

These have now been completed; closing this issue.
